// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/boshangad/v1/ent/authitemchild"
)

// AuthItemChildCreate is the builder for creating a AuthItemChild entity.
type AuthItemChildCreate struct {
	config
	mutation *AuthItemChildMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// Mutation returns the AuthItemChildMutation object of the builder.
func (aicc *AuthItemChildCreate) Mutation() *AuthItemChildMutation {
	return aicc.mutation
}

// Save creates the AuthItemChild in the database.
func (aicc *AuthItemChildCreate) Save(ctx context.Context) (*AuthItemChild, error) {
	var (
		err  error
		node *AuthItemChild
	)
	if len(aicc.hooks) == 0 {
		if err = aicc.check(); err != nil {
			return nil, err
		}
		node, err = aicc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AuthItemChildMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = aicc.check(); err != nil {
				return nil, err
			}
			aicc.mutation = mutation
			if node, err = aicc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(aicc.hooks) - 1; i >= 0; i-- {
			if aicc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aicc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aicc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (aicc *AuthItemChildCreate) SaveX(ctx context.Context) *AuthItemChild {
	v, err := aicc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aicc *AuthItemChildCreate) Exec(ctx context.Context) error {
	_, err := aicc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aicc *AuthItemChildCreate) ExecX(ctx context.Context) {
	if err := aicc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aicc *AuthItemChildCreate) check() error {
	return nil
}

func (aicc *AuthItemChildCreate) sqlSave(ctx context.Context) (*AuthItemChild, error) {
	_node, _spec := aicc.createSpec()
	if err := sqlgraph.CreateNode(ctx, aicc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (aicc *AuthItemChildCreate) createSpec() (*AuthItemChild, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthItemChild{config: aicc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: authitemchild.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: authitemchild.FieldID,
			},
		}
	)
	_spec.Schema = aicc.schemaConfig.AuthItemChild
	_spec.OnConflict = aicc.conflict
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthItemChild.Create().
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (aicc *AuthItemChildCreate) OnConflict(opts ...sql.ConflictOption) *AuthItemChildUpsertOne {
	aicc.conflict = opts
	return &AuthItemChildUpsertOne{
		create: aicc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthItemChild.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (aicc *AuthItemChildCreate) OnConflictColumns(columns ...string) *AuthItemChildUpsertOne {
	aicc.conflict = append(aicc.conflict, sql.ConflictColumns(columns...))
	return &AuthItemChildUpsertOne{
		create: aicc,
	}
}

type (
	// AuthItemChildUpsertOne is the builder for "upsert"-ing
	//  one AuthItemChild node.
	AuthItemChildUpsertOne struct {
		create *AuthItemChildCreate
	}

	// AuthItemChildUpsert is the "OnConflict" setter.
	AuthItemChildUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AuthItemChild.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *AuthItemChildUpsertOne) UpdateNewValues() *AuthItemChildUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.AuthItemChild.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *AuthItemChildUpsertOne) Ignore() *AuthItemChildUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthItemChildUpsertOne) DoNothing() *AuthItemChildUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthItemChildCreate.OnConflict
// documentation for more info.
func (u *AuthItemChildUpsertOne) Update(set func(*AuthItemChildUpsert)) *AuthItemChildUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthItemChildUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *AuthItemChildUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthItemChildCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthItemChildUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuthItemChildUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuthItemChildUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuthItemChildCreateBulk is the builder for creating many AuthItemChild entities in bulk.
type AuthItemChildCreateBulk struct {
	config
	builders []*AuthItemChildCreate
	conflict []sql.ConflictOption
}

// Save creates the AuthItemChild entities in the database.
func (aiccb *AuthItemChildCreateBulk) Save(ctx context.Context) ([]*AuthItemChild, error) {
	specs := make([]*sqlgraph.CreateSpec, len(aiccb.builders))
	nodes := make([]*AuthItemChild, len(aiccb.builders))
	mutators := make([]Mutator, len(aiccb.builders))
	for i := range aiccb.builders {
		func(i int, root context.Context) {
			builder := aiccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthItemChildMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, aiccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = aiccb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, aiccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, aiccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (aiccb *AuthItemChildCreateBulk) SaveX(ctx context.Context) []*AuthItemChild {
	v, err := aiccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aiccb *AuthItemChildCreateBulk) Exec(ctx context.Context) error {
	_, err := aiccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aiccb *AuthItemChildCreateBulk) ExecX(ctx context.Context) {
	if err := aiccb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthItemChild.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (aiccb *AuthItemChildCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuthItemChildUpsertBulk {
	aiccb.conflict = opts
	return &AuthItemChildUpsertBulk{
		create: aiccb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthItemChild.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (aiccb *AuthItemChildCreateBulk) OnConflictColumns(columns ...string) *AuthItemChildUpsertBulk {
	aiccb.conflict = append(aiccb.conflict, sql.ConflictColumns(columns...))
	return &AuthItemChildUpsertBulk{
		create: aiccb,
	}
}

// AuthItemChildUpsertBulk is the builder for "upsert"-ing
// a bulk of AuthItemChild nodes.
type AuthItemChildUpsertBulk struct {
	create *AuthItemChildCreateBulk
}

// UpdateNewValues updates the fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuthItemChild.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *AuthItemChildUpsertBulk) UpdateNewValues() *AuthItemChildUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthItemChild.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *AuthItemChildUpsertBulk) Ignore() *AuthItemChildUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthItemChildUpsertBulk) DoNothing() *AuthItemChildUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthItemChildCreateBulk.OnConflict
// documentation for more info.
func (u *AuthItemChildUpsertBulk) Update(set func(*AuthItemChildUpsert)) *AuthItemChildUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthItemChildUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *AuthItemChildUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuthItemChildCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthItemChildCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthItemChildUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
