// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/boshangad/v1/ent/app"
	"github.com/boshangad/v1/ent/appoption"
	"github.com/boshangad/v1/ent/appuser"
	"github.com/boshangad/v1/ent/appuserloginlog"
	"github.com/boshangad/v1/ent/appusertoken"
	"github.com/boshangad/v1/ent/emaillog"
	"github.com/boshangad/v1/ent/schema"
	"github.com/boshangad/v1/ent/smslog"
	"github.com/boshangad/v1/ent/sort"
	"github.com/boshangad/v1/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appMixin := schema.App{}.Mixin()
	appMixinFields1 := appMixin[1].Fields()
	_ = appMixinFields1
	appMixinFields2 := appMixin[2].Fields()
	_ = appMixinFields2
	appMixinFields3 := appMixin[3].Fields()
	_ = appMixinFields3
	appMixinFields4 := appMixin[4].Fields()
	_ = appMixinFields4
	appMixinFields5 := appMixin[5].Fields()
	_ = appMixinFields5
	appFields := schema.App{}.Fields()
	_ = appFields
	// appDescDeleteTime is the schema descriptor for delete_time field.
	appDescDeleteTime := appMixinFields1[0].Descriptor()
	// app.DefaultDeleteTime holds the default value on creation for the delete_time field.
	app.DefaultDeleteTime = appDescDeleteTime.Default.(int64)
	// appDescCreateTime is the schema descriptor for create_time field.
	appDescCreateTime := appMixinFields2[0].Descriptor()
	// app.DefaultCreateTime holds the default value on creation for the create_time field.
	app.DefaultCreateTime = appDescCreateTime.Default.(func() int64)
	// appDescCreateBy is the schema descriptor for create_by field.
	appDescCreateBy := appMixinFields3[0].Descriptor()
	// app.DefaultCreateBy holds the default value on creation for the create_by field.
	app.DefaultCreateBy = appDescCreateBy.Default.(uint64)
	// appDescUpdateTime is the schema descriptor for update_time field.
	appDescUpdateTime := appMixinFields4[0].Descriptor()
	// app.DefaultUpdateTime holds the default value on creation for the update_time field.
	app.DefaultUpdateTime = appDescUpdateTime.Default.(func() int64)
	// app.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	app.UpdateDefaultUpdateTime = appDescUpdateTime.UpdateDefault.(func() int64)
	// appDescUpdateBy is the schema descriptor for update_by field.
	appDescUpdateBy := appMixinFields5[0].Descriptor()
	// app.DefaultUpdateBy holds the default value on creation for the update_by field.
	app.DefaultUpdateBy = appDescUpdateBy.Default.(uint64)
	// appDescUUID is the schema descriptor for uuid field.
	appDescUUID := appFields[0].Descriptor()
	// app.DefaultUUID holds the default value on creation for the uuid field.
	app.DefaultUUID = appDescUUID.Default.(func() *uuid.UUID)
	// appDescTypeID is the schema descriptor for type_id field.
	appDescTypeID := appFields[1].Descriptor()
	// app.DefaultTypeID holds the default value on creation for the type_id field.
	app.DefaultTypeID = appDescTypeID.Default.(uint64)
	// appDescTitle is the schema descriptor for title field.
	appDescTitle := appFields[2].Descriptor()
	// app.DefaultTitle holds the default value on creation for the title field.
	app.DefaultTitle = appDescTitle.Default.(string)
	// app.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	app.TitleValidator = appDescTitle.Validators[0].(func(string) error)
	// appDescIntro is the schema descriptor for intro field.
	appDescIntro := appFields[3].Descriptor()
	// app.DefaultIntro holds the default value on creation for the intro field.
	app.DefaultIntro = appDescIntro.Default.(string)
	// app.IntroValidator is a validator for the "intro" field. It is called by the builders before save.
	app.IntroValidator = appDescIntro.Validators[0].(func(string) error)
	// appDescMpOriginID is the schema descriptor for mp_origin_id field.
	appDescMpOriginID := appFields[4].Descriptor()
	// app.DefaultMpOriginID holds the default value on creation for the mp_origin_id field.
	app.DefaultMpOriginID = appDescMpOriginID.Default.(string)
	// app.MpOriginIDValidator is a validator for the "mp_origin_id" field. It is called by the builders before save.
	app.MpOriginIDValidator = appDescMpOriginID.Validators[0].(func(string) error)
	// appDescAppID is the schema descriptor for app_id field.
	appDescAppID := appFields[5].Descriptor()
	// app.DefaultAppID holds the default value on creation for the app_id field.
	app.DefaultAppID = appDescAppID.Default.(string)
	// app.AppIDValidator is a validator for the "app_id" field. It is called by the builders before save.
	app.AppIDValidator = appDescAppID.Validators[0].(func(string) error)
	// appDescAppSecret is the schema descriptor for app_secret field.
	appDescAppSecret := appFields[6].Descriptor()
	// app.DefaultAppSecret holds the default value on creation for the app_secret field.
	app.DefaultAppSecret = appDescAppSecret.Default.(string)
	// app.AppSecretValidator is a validator for the "app_secret" field. It is called by the builders before save.
	app.AppSecretValidator = appDescAppSecret.Validators[0].(func(string) error)
	// appDescHasPaymentAuth is the schema descriptor for has_payment_auth field.
	appDescHasPaymentAuth := appFields[7].Descriptor()
	// app.DefaultHasPaymentAuth holds the default value on creation for the has_payment_auth field.
	app.DefaultHasPaymentAuth = appDescHasPaymentAuth.Default.(bool)
	// appDescRegisterUserNumber is the schema descriptor for register_user_number field.
	appDescRegisterUserNumber := appFields[8].Descriptor()
	// app.DefaultRegisterUserNumber holds the default value on creation for the register_user_number field.
	app.DefaultRegisterUserNumber = appDescRegisterUserNumber.Default.(uint64)
	// appDescStatus is the schema descriptor for status field.
	appDescStatus := appFields[9].Descriptor()
	// app.DefaultStatus holds the default value on creation for the status field.
	app.DefaultStatus = appDescStatus.Default.(uint)
	// app.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	app.StatusValidator = appDescStatus.Validators[0].(func(uint) error)
	appoptionMixin := schema.AppOption{}.Mixin()
	appoptionMixinFields1 := appoptionMixin[1].Fields()
	_ = appoptionMixinFields1
	appoptionMixinFields2 := appoptionMixin[2].Fields()
	_ = appoptionMixinFields2
	appoptionMixinFields3 := appoptionMixin[3].Fields()
	_ = appoptionMixinFields3
	appoptionMixinFields4 := appoptionMixin[4].Fields()
	_ = appoptionMixinFields4
	appoptionFields := schema.AppOption{}.Fields()
	_ = appoptionFields
	// appoptionDescCreateTime is the schema descriptor for create_time field.
	appoptionDescCreateTime := appoptionMixinFields1[0].Descriptor()
	// appoption.DefaultCreateTime holds the default value on creation for the create_time field.
	appoption.DefaultCreateTime = appoptionDescCreateTime.Default.(func() int64)
	// appoptionDescCreateBy is the schema descriptor for create_by field.
	appoptionDescCreateBy := appoptionMixinFields2[0].Descriptor()
	// appoption.DefaultCreateBy holds the default value on creation for the create_by field.
	appoption.DefaultCreateBy = appoptionDescCreateBy.Default.(uint64)
	// appoptionDescUpdateTime is the schema descriptor for update_time field.
	appoptionDescUpdateTime := appoptionMixinFields3[0].Descriptor()
	// appoption.DefaultUpdateTime holds the default value on creation for the update_time field.
	appoption.DefaultUpdateTime = appoptionDescUpdateTime.Default.(func() int64)
	// appoption.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	appoption.UpdateDefaultUpdateTime = appoptionDescUpdateTime.UpdateDefault.(func() int64)
	// appoptionDescUpdateBy is the schema descriptor for update_by field.
	appoptionDescUpdateBy := appoptionMixinFields4[0].Descriptor()
	// appoption.DefaultUpdateBy holds the default value on creation for the update_by field.
	appoption.DefaultUpdateBy = appoptionDescUpdateBy.Default.(uint64)
	// appoptionDescAppID is the schema descriptor for app_id field.
	appoptionDescAppID := appoptionFields[0].Descriptor()
	// appoption.DefaultAppID holds the default value on creation for the app_id field.
	appoption.DefaultAppID = appoptionDescAppID.Default.(uint64)
	// appoptionDescTitle is the schema descriptor for title field.
	appoptionDescTitle := appoptionFields[1].Descriptor()
	// appoption.DefaultTitle holds the default value on creation for the title field.
	appoption.DefaultTitle = appoptionDescTitle.Default.(string)
	// appoption.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	appoption.TitleValidator = appoptionDescTitle.Validators[0].(func(string) error)
	// appoptionDescDescription is the schema descriptor for description field.
	appoptionDescDescription := appoptionFields[2].Descriptor()
	// appoption.DefaultDescription holds the default value on creation for the description field.
	appoption.DefaultDescription = appoptionDescDescription.Default.(string)
	// appoption.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	appoption.DescriptionValidator = appoptionDescDescription.Validators[0].(func(string) error)
	// appoptionDescName is the schema descriptor for name field.
	appoptionDescName := appoptionFields[3].Descriptor()
	// appoption.DefaultName holds the default value on creation for the name field.
	appoption.DefaultName = appoptionDescName.Default.(string)
	// appoption.NameValidator is a validator for the "name" field. It is called by the builders before save.
	appoption.NameValidator = appoptionDescName.Validators[0].(func(string) error)
	// appoptionDescValue is the schema descriptor for value field.
	appoptionDescValue := appoptionFields[4].Descriptor()
	// appoption.DefaultValue holds the default value on creation for the value field.
	appoption.DefaultValue = appoptionDescValue.Default.(string)
	// appoption.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	appoption.ValueValidator = appoptionDescValue.Validators[0].(func(string) error)
	// appoptionDescExpireTime is the schema descriptor for expire_time field.
	appoptionDescExpireTime := appoptionFields[5].Descriptor()
	// appoption.DefaultExpireTime holds the default value on creation for the expire_time field.
	appoption.DefaultExpireTime = appoptionDescExpireTime.Default.(int64)
	// appoptionDescEditType is the schema descriptor for edit_type field.
	appoptionDescEditType := appoptionFields[6].Descriptor()
	// appoption.DefaultEditType holds the default value on creation for the edit_type field.
	appoption.DefaultEditType = appoptionDescEditType.Default.(uint)
	appuserMixin := schema.AppUser{}.Mixin()
	appuserMixinFields1 := appuserMixin[1].Fields()
	_ = appuserMixinFields1
	appuserMixinFields2 := appuserMixin[2].Fields()
	_ = appuserMixinFields2
	appuserFields := schema.AppUser{}.Fields()
	_ = appuserFields
	// appuserDescCreateTime is the schema descriptor for create_time field.
	appuserDescCreateTime := appuserMixinFields1[0].Descriptor()
	// appuser.DefaultCreateTime holds the default value on creation for the create_time field.
	appuser.DefaultCreateTime = appuserDescCreateTime.Default.(func() int64)
	// appuserDescUpdateTime is the schema descriptor for update_time field.
	appuserDescUpdateTime := appuserMixinFields2[0].Descriptor()
	// appuser.DefaultUpdateTime holds the default value on creation for the update_time field.
	appuser.DefaultUpdateTime = appuserDescUpdateTime.Default.(func() int64)
	// appuser.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	appuser.UpdateDefaultUpdateTime = appuserDescUpdateTime.UpdateDefault.(func() int64)
	// appuserDescAppID is the schema descriptor for app_id field.
	appuserDescAppID := appuserFields[0].Descriptor()
	// appuser.DefaultAppID holds the default value on creation for the app_id field.
	appuser.DefaultAppID = appuserDescAppID.Default.(uint64)
	// appuserDescUserID is the schema descriptor for user_id field.
	appuserDescUserID := appuserFields[1].Descriptor()
	// appuser.DefaultUserID holds the default value on creation for the user_id field.
	appuser.DefaultUserID = appuserDescUserID.Default.(uint64)
	// appuserDescOpenID is the schema descriptor for open_id field.
	appuserDescOpenID := appuserFields[2].Descriptor()
	// appuser.DefaultOpenID holds the default value on creation for the open_id field.
	appuser.DefaultOpenID = appuserDescOpenID.Default.(string)
	// appuser.OpenIDValidator is a validator for the "open_id" field. It is called by the builders before save.
	appuser.OpenIDValidator = appuserDescOpenID.Validators[0].(func(string) error)
	// appuserDescUnionid is the schema descriptor for unionid field.
	appuserDescUnionid := appuserFields[3].Descriptor()
	// appuser.DefaultUnionid holds the default value on creation for the unionid field.
	appuser.DefaultUnionid = appuserDescUnionid.Default.(string)
	// appuser.UnionidValidator is a validator for the "unionid" field. It is called by the builders before save.
	appuser.UnionidValidator = appuserDescUnionid.Validators[0].(func(string) error)
	// appuserDescSessionKey is the schema descriptor for session_key field.
	appuserDescSessionKey := appuserFields[4].Descriptor()
	// appuser.DefaultSessionKey holds the default value on creation for the session_key field.
	appuser.DefaultSessionKey = appuserDescSessionKey.Default.(string)
	// appuser.SessionKeyValidator is a validator for the "session_key" field. It is called by the builders before save.
	appuser.SessionKeyValidator = appuserDescSessionKey.Validators[0].(func(string) error)
	// appuserDescIsLoadUserProfile is the schema descriptor for is_load_user_profile field.
	appuserDescIsLoadUserProfile := appuserFields[5].Descriptor()
	// appuser.DefaultIsLoadUserProfile holds the default value on creation for the is_load_user_profile field.
	appuser.DefaultIsLoadUserProfile = appuserDescIsLoadUserProfile.Default.(bool)
	// appuserDescNickname is the schema descriptor for nickname field.
	appuserDescNickname := appuserFields[6].Descriptor()
	// appuser.DefaultNickname holds the default value on creation for the nickname field.
	appuser.DefaultNickname = appuserDescNickname.Default.(string)
	// appuser.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	appuser.NicknameValidator = appuserDescNickname.Validators[0].(func(string) error)
	// appuserDescAvatar is the schema descriptor for avatar field.
	appuserDescAvatar := appuserFields[7].Descriptor()
	// appuser.DefaultAvatar holds the default value on creation for the avatar field.
	appuser.DefaultAvatar = appuserDescAvatar.Default.(string)
	// appuser.AvatarValidator is a validator for the "avatar" field. It is called by the builders before save.
	appuser.AvatarValidator = appuserDescAvatar.Validators[0].(func(string) error)
	// appuserDescAvatarURL is the schema descriptor for avatar_url field.
	appuserDescAvatarURL := appuserFields[8].Descriptor()
	// appuser.DefaultAvatarURL holds the default value on creation for the avatar_url field.
	appuser.DefaultAvatarURL = appuserDescAvatarURL.Default.(string)
	// appuser.AvatarURLValidator is a validator for the "avatar_url" field. It is called by the builders before save.
	appuser.AvatarURLValidator = appuserDescAvatarURL.Validators[0].(func(string) error)
	// appuserDescGender is the schema descriptor for gender field.
	appuserDescGender := appuserFields[9].Descriptor()
	// appuser.DefaultGender holds the default value on creation for the gender field.
	appuser.DefaultGender = appuserDescGender.Default.(uint)
	// appuser.GenderValidator is a validator for the "gender" field. It is called by the builders before save.
	appuser.GenderValidator = appuserDescGender.Validators[0].(func(uint) error)
	// appuserDescCounty is the schema descriptor for county field.
	appuserDescCounty := appuserFields[10].Descriptor()
	// appuser.DefaultCounty holds the default value on creation for the county field.
	appuser.DefaultCounty = appuserDescCounty.Default.(string)
	// appuser.CountyValidator is a validator for the "county" field. It is called by the builders before save.
	appuser.CountyValidator = appuserDescCounty.Validators[0].(func(string) error)
	// appuserDescCountryCode is the schema descriptor for country_code field.
	appuserDescCountryCode := appuserFields[11].Descriptor()
	// appuser.DefaultCountryCode holds the default value on creation for the country_code field.
	appuser.DefaultCountryCode = appuserDescCountryCode.Default.(string)
	// appuser.CountryCodeValidator is a validator for the "country_code" field. It is called by the builders before save.
	appuser.CountryCodeValidator = appuserDescCountryCode.Validators[0].(func(string) error)
	// appuserDescProvince is the schema descriptor for province field.
	appuserDescProvince := appuserFields[12].Descriptor()
	// appuser.DefaultProvince holds the default value on creation for the province field.
	appuser.DefaultProvince = appuserDescProvince.Default.(string)
	// appuser.ProvinceValidator is a validator for the "province" field. It is called by the builders before save.
	appuser.ProvinceValidator = appuserDescProvince.Validators[0].(func(string) error)
	// appuserDescCity is the schema descriptor for city field.
	appuserDescCity := appuserFields[13].Descriptor()
	// appuser.DefaultCity holds the default value on creation for the city field.
	appuser.DefaultCity = appuserDescCity.Default.(string)
	// appuser.CityValidator is a validator for the "city" field. It is called by the builders before save.
	appuser.CityValidator = appuserDescCity.Validators[0].(func(string) error)
	// appuserDescLanguage is the schema descriptor for language field.
	appuserDescLanguage := appuserFields[14].Descriptor()
	// appuser.DefaultLanguage holds the default value on creation for the language field.
	appuser.DefaultLanguage = appuserDescLanguage.Default.(string)
	// appuser.LanguageValidator is a validator for the "language" field. It is called by the builders before save.
	appuser.LanguageValidator = appuserDescLanguage.Validators[0].(func(string) error)
	// appuserDescPhoneNumber is the schema descriptor for phone_number field.
	appuserDescPhoneNumber := appuserFields[15].Descriptor()
	// appuser.DefaultPhoneNumber holds the default value on creation for the phone_number field.
	appuser.DefaultPhoneNumber = appuserDescPhoneNumber.Default.(string)
	// appuser.PhoneNumberValidator is a validator for the "phone_number" field. It is called by the builders before save.
	appuser.PhoneNumberValidator = appuserDescPhoneNumber.Validators[0].(func(string) error)
	// appuserDescPurePhoneNumber is the schema descriptor for pure_phone_number field.
	appuserDescPurePhoneNumber := appuserFields[16].Descriptor()
	// appuser.DefaultPurePhoneNumber holds the default value on creation for the pure_phone_number field.
	appuser.DefaultPurePhoneNumber = appuserDescPurePhoneNumber.Default.(string)
	// appuser.PurePhoneNumberValidator is a validator for the "pure_phone_number" field. It is called by the builders before save.
	appuser.PurePhoneNumberValidator = appuserDescPurePhoneNumber.Validators[0].(func(string) error)
	// appuserDescWatermark is the schema descriptor for watermark field.
	appuserDescWatermark := appuserFields[17].Descriptor()
	// appuser.DefaultWatermark holds the default value on creation for the watermark field.
	appuser.DefaultWatermark = appuserDescWatermark.Default.(string)
	// appuser.WatermarkValidator is a validator for the "watermark" field. It is called by the builders before save.
	appuser.WatermarkValidator = appuserDescWatermark.Validators[0].(func(string) error)
	// appuserDescLoadUserProfileTime is the schema descriptor for load_user_profile_time field.
	appuserDescLoadUserProfileTime := appuserFields[18].Descriptor()
	// appuser.DefaultLoadUserProfileTime holds the default value on creation for the load_user_profile_time field.
	appuser.DefaultLoadUserProfileTime = appuserDescLoadUserProfileTime.Default.(int64)
	// appuserDescLastLoginTime is the schema descriptor for last_login_time field.
	appuserDescLastLoginTime := appuserFields[19].Descriptor()
	// appuser.DefaultLastLoginTime holds the default value on creation for the last_login_time field.
	appuser.DefaultLastLoginTime = appuserDescLastLoginTime.Default.(int64)
	appuserloginlogMixin := schema.AppUserLoginLog{}.Mixin()
	appuserloginlogMixinFields1 := appuserloginlogMixin[1].Fields()
	_ = appuserloginlogMixinFields1
	appuserloginlogFields := schema.AppUserLoginLog{}.Fields()
	_ = appuserloginlogFields
	// appuserloginlogDescCreateTime is the schema descriptor for create_time field.
	appuserloginlogDescCreateTime := appuserloginlogMixinFields1[0].Descriptor()
	// appuserloginlog.DefaultCreateTime holds the default value on creation for the create_time field.
	appuserloginlog.DefaultCreateTime = appuserloginlogDescCreateTime.Default.(func() int64)
	// appuserloginlogDescAppID is the schema descriptor for app_id field.
	appuserloginlogDescAppID := appuserloginlogFields[0].Descriptor()
	// appuserloginlog.DefaultAppID holds the default value on creation for the app_id field.
	appuserloginlog.DefaultAppID = appuserloginlogDescAppID.Default.(uint64)
	// appuserloginlogDescAppUserID is the schema descriptor for app_user_id field.
	appuserloginlogDescAppUserID := appuserloginlogFields[1].Descriptor()
	// appuserloginlog.DefaultAppUserID holds the default value on creation for the app_user_id field.
	appuserloginlog.DefaultAppUserID = appuserloginlogDescAppUserID.Default.(uint64)
	// appuserloginlogDescUserID is the schema descriptor for user_id field.
	appuserloginlogDescUserID := appuserloginlogFields[2].Descriptor()
	// appuserloginlog.DefaultUserID holds the default value on creation for the user_id field.
	appuserloginlog.DefaultUserID = appuserloginlogDescUserID.Default.(uint64)
	// appuserloginlogDescLoginTypeID is the schema descriptor for login_type_id field.
	appuserloginlogDescLoginTypeID := appuserloginlogFields[3].Descriptor()
	// appuserloginlog.DefaultLoginTypeID holds the default value on creation for the login_type_id field.
	appuserloginlog.DefaultLoginTypeID = appuserloginlogDescLoginTypeID.Default.(uint)
	// appuserloginlogDescIP is the schema descriptor for ip field.
	appuserloginlogDescIP := appuserloginlogFields[4].Descriptor()
	// appuserloginlog.DefaultIP holds the default value on creation for the ip field.
	appuserloginlog.DefaultIP = appuserloginlogDescIP.Default.(string)
	// appuserloginlog.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	appuserloginlog.IPValidator = appuserloginlogDescIP.Validators[0].(func(string) error)
	// appuserloginlogDescUserAgent is the schema descriptor for user_agent field.
	appuserloginlogDescUserAgent := appuserloginlogFields[5].Descriptor()
	// appuserloginlog.DefaultUserAgent holds the default value on creation for the user_agent field.
	appuserloginlog.DefaultUserAgent = appuserloginlogDescUserAgent.Default.(string)
	// appuserloginlog.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	appuserloginlog.UserAgentValidator = appuserloginlogDescUserAgent.Validators[0].(func(string) error)
	// appuserloginlogDescClientVersion is the schema descriptor for client_version field.
	appuserloginlogDescClientVersion := appuserloginlogFields[6].Descriptor()
	// appuserloginlog.DefaultClientVersion holds the default value on creation for the client_version field.
	appuserloginlog.DefaultClientVersion = appuserloginlogDescClientVersion.Default.(string)
	// appuserloginlog.ClientVersionValidator is a validator for the "client_version" field. It is called by the builders before save.
	appuserloginlog.ClientVersionValidator = appuserloginlogDescClientVersion.Validators[0].(func(string) error)
	// appuserloginlogDescStatus is the schema descriptor for status field.
	appuserloginlogDescStatus := appuserloginlogFields[8].Descriptor()
	// appuserloginlog.DefaultStatus holds the default value on creation for the status field.
	appuserloginlog.DefaultStatus = appuserloginlogDescStatus.Default.(uint)
	appusertokenMixin := schema.AppUserToken{}.Mixin()
	appusertokenMixinFields1 := appusertokenMixin[1].Fields()
	_ = appusertokenMixinFields1
	appusertokenFields := schema.AppUserToken{}.Fields()
	_ = appusertokenFields
	// appusertokenDescCreateTime is the schema descriptor for create_time field.
	appusertokenDescCreateTime := appusertokenMixinFields1[0].Descriptor()
	// appusertoken.DefaultCreateTime holds the default value on creation for the create_time field.
	appusertoken.DefaultCreateTime = appusertokenDescCreateTime.Default.(func() int64)
	// appusertokenDescAppID is the schema descriptor for app_id field.
	appusertokenDescAppID := appusertokenFields[0].Descriptor()
	// appusertoken.DefaultAppID holds the default value on creation for the app_id field.
	appusertoken.DefaultAppID = appusertokenDescAppID.Default.(uint64)
	// appusertokenDescAppUserID is the schema descriptor for app_user_id field.
	appusertokenDescAppUserID := appusertokenFields[1].Descriptor()
	// appusertoken.DefaultAppUserID holds the default value on creation for the app_user_id field.
	appusertoken.DefaultAppUserID = appusertokenDescAppUserID.Default.(uint64)
	// appusertokenDescUserID is the schema descriptor for user_id field.
	appusertokenDescUserID := appusertokenFields[2].Descriptor()
	// appusertoken.DefaultUserID holds the default value on creation for the user_id field.
	appusertoken.DefaultUserID = appusertokenDescUserID.Default.(uint64)
	// appusertokenDescUserAgent is the schema descriptor for user_agent field.
	appusertokenDescUserAgent := appusertokenFields[3].Descriptor()
	// appusertoken.DefaultUserAgent holds the default value on creation for the user_agent field.
	appusertoken.DefaultUserAgent = appusertokenDescUserAgent.Default.(string)
	// appusertoken.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	appusertoken.UserAgentValidator = appusertokenDescUserAgent.Validators[0].(func(string) error)
	// appusertokenDescClientVersion is the schema descriptor for client_version field.
	appusertokenDescClientVersion := appusertokenFields[4].Descriptor()
	// appusertoken.DefaultClientVersion holds the default value on creation for the client_version field.
	appusertoken.DefaultClientVersion = appusertokenDescClientVersion.Default.(string)
	// appusertoken.ClientVersionValidator is a validator for the "client_version" field. It is called by the builders before save.
	appusertoken.ClientVersionValidator = appusertokenDescClientVersion.Validators[0].(func(string) error)
	// appusertokenDescUUID is the schema descriptor for uuid field.
	appusertokenDescUUID := appusertokenFields[5].Descriptor()
	// appusertoken.DefaultUUID holds the default value on creation for the uuid field.
	appusertoken.DefaultUUID = appusertokenDescUUID.Default.(func() *uuid.UUID)
	// appusertokenDescIP is the schema descriptor for ip field.
	appusertokenDescIP := appusertokenFields[6].Descriptor()
	// appusertoken.DefaultIP holds the default value on creation for the ip field.
	appusertoken.DefaultIP = appusertokenDescIP.Default.(string)
	// appusertoken.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	appusertoken.IPValidator = appusertokenDescIP.Validators[0].(func(string) error)
	// appusertokenDescExpireTime is the schema descriptor for expire_time field.
	appusertokenDescExpireTime := appusertokenFields[7].Descriptor()
	// appusertoken.DefaultExpireTime holds the default value on creation for the expire_time field.
	appusertoken.DefaultExpireTime = appusertokenDescExpireTime.Default.(int64)
	emaillogMixin := schema.EmailLog{}.Mixin()
	emaillogMixinFields1 := emaillogMixin[1].Fields()
	_ = emaillogMixinFields1
	emaillogMixinFields2 := emaillogMixin[2].Fields()
	_ = emaillogMixinFields2
	emaillogMixinFields3 := emaillogMixin[3].Fields()
	_ = emaillogMixinFields3
	emaillogMixinFields4 := emaillogMixin[4].Fields()
	_ = emaillogMixinFields4
	emaillogFields := schema.EmailLog{}.Fields()
	_ = emaillogFields
	// emaillogDescCreateTime is the schema descriptor for create_time field.
	emaillogDescCreateTime := emaillogMixinFields1[0].Descriptor()
	// emaillog.DefaultCreateTime holds the default value on creation for the create_time field.
	emaillog.DefaultCreateTime = emaillogDescCreateTime.Default.(func() int64)
	// emaillogDescCreateBy is the schema descriptor for create_by field.
	emaillogDescCreateBy := emaillogMixinFields2[0].Descriptor()
	// emaillog.DefaultCreateBy holds the default value on creation for the create_by field.
	emaillog.DefaultCreateBy = emaillogDescCreateBy.Default.(uint64)
	// emaillogDescUpdateTime is the schema descriptor for update_time field.
	emaillogDescUpdateTime := emaillogMixinFields3[0].Descriptor()
	// emaillog.DefaultUpdateTime holds the default value on creation for the update_time field.
	emaillog.DefaultUpdateTime = emaillogDescUpdateTime.Default.(func() int64)
	// emaillog.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	emaillog.UpdateDefaultUpdateTime = emaillogDescUpdateTime.UpdateDefault.(func() int64)
	// emaillogDescUpdateBy is the schema descriptor for update_by field.
	emaillogDescUpdateBy := emaillogMixinFields4[0].Descriptor()
	// emaillog.DefaultUpdateBy holds the default value on creation for the update_by field.
	emaillog.DefaultUpdateBy = emaillogDescUpdateBy.Default.(uint64)
	// emaillogDescAppID is the schema descriptor for app_id field.
	emaillogDescAppID := emaillogFields[0].Descriptor()
	// emaillog.DefaultAppID holds the default value on creation for the app_id field.
	emaillog.DefaultAppID = emaillogDescAppID.Default.(uint64)
	// emaillogDescEmail is the schema descriptor for email field.
	emaillogDescEmail := emaillogFields[1].Descriptor()
	// emaillog.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	emaillog.EmailValidator = emaillogDescEmail.Validators[0].(func(string) error)
	// emaillogDescScope is the schema descriptor for scope field.
	emaillogDescScope := emaillogFields[2].Descriptor()
	// emaillog.DefaultScope holds the default value on creation for the scope field.
	emaillog.DefaultScope = emaillogDescScope.Default.(string)
	// emaillog.ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	emaillog.ScopeValidator = emaillogDescScope.Validators[0].(func(string) error)
	// emaillogDescTypeID is the schema descriptor for type_id field.
	emaillogDescTypeID := emaillogFields[3].Descriptor()
	// emaillog.DefaultTypeID holds the default value on creation for the type_id field.
	emaillog.DefaultTypeID = emaillogDescTypeID.Default.(uint64)
	// emaillogDescGateway is the schema descriptor for gateway field.
	emaillogDescGateway := emaillogFields[4].Descriptor()
	// emaillog.DefaultGateway holds the default value on creation for the gateway field.
	emaillog.DefaultGateway = emaillogDescGateway.Default.(string)
	// emaillog.GatewayValidator is a validator for the "gateway" field. It is called by the builders before save.
	emaillog.GatewayValidator = emaillogDescGateway.Validators[0].(func(string) error)
	// emaillogDescIP is the schema descriptor for ip field.
	emaillogDescIP := emaillogFields[5].Descriptor()
	// emaillog.DefaultIP holds the default value on creation for the ip field.
	emaillog.DefaultIP = emaillogDescIP.Default.(string)
	// emaillog.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	emaillog.IPValidator = emaillogDescIP.Validators[0].(func(string) error)
	// emaillogDescFromName is the schema descriptor for from_name field.
	emaillogDescFromName := emaillogFields[6].Descriptor()
	// emaillog.DefaultFromName holds the default value on creation for the from_name field.
	emaillog.DefaultFromName = emaillogDescFromName.Default.(string)
	// emaillog.FromNameValidator is a validator for the "from_name" field. It is called by the builders before save.
	emaillog.FromNameValidator = emaillogDescFromName.Validators[0].(func(string) error)
	// emaillogDescFromAddress is the schema descriptor for from_address field.
	emaillogDescFromAddress := emaillogFields[7].Descriptor()
	// emaillog.DefaultFromAddress holds the default value on creation for the from_address field.
	emaillog.DefaultFromAddress = emaillogDescFromAddress.Default.(string)
	// emaillog.FromAddressValidator is a validator for the "from_address" field. It is called by the builders before save.
	emaillog.FromAddressValidator = emaillogDescFromAddress.Validators[0].(func(string) error)
	// emaillogDescTitle is the schema descriptor for title field.
	emaillogDescTitle := emaillogFields[8].Descriptor()
	// emaillog.DefaultTitle holds the default value on creation for the title field.
	emaillog.DefaultTitle = emaillogDescTitle.Default.(string)
	// emaillog.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	emaillog.TitleValidator = emaillogDescTitle.Validators[0].(func(string) error)
	// emaillogDescContent is the schema descriptor for content field.
	emaillogDescContent := emaillogFields[9].Descriptor()
	// emaillog.DefaultContent holds the default value on creation for the content field.
	emaillog.DefaultContent = emaillogDescContent.Default.(string)
	// emaillogDescData is the schema descriptor for data field.
	emaillogDescData := emaillogFields[10].Descriptor()
	// emaillog.DefaultData holds the default value on creation for the data field.
	emaillog.DefaultData = emaillogDescData.Default.(string)
	// emaillog.DataValidator is a validator for the "data" field. It is called by the builders before save.
	emaillog.DataValidator = emaillogDescData.Validators[0].(func(string) error)
	// emaillogDescCheckCount is the schema descriptor for check_count field.
	emaillogDescCheckCount := emaillogFields[11].Descriptor()
	// emaillog.DefaultCheckCount holds the default value on creation for the check_count field.
	emaillog.DefaultCheckCount = emaillogDescCheckCount.Default.(uint8)
	// emaillogDescStatus is the schema descriptor for status field.
	emaillogDescStatus := emaillogFields[12].Descriptor()
	// emaillog.DefaultStatus holds the default value on creation for the status field.
	emaillog.DefaultStatus = emaillogDescStatus.Default.(uint)
	// emaillogDescReturnMsg is the schema descriptor for return_msg field.
	emaillogDescReturnMsg := emaillogFields[13].Descriptor()
	// emaillog.DefaultReturnMsg holds the default value on creation for the return_msg field.
	emaillog.DefaultReturnMsg = emaillogDescReturnMsg.Default.(string)
	// emaillog.ReturnMsgValidator is a validator for the "return_msg" field. It is called by the builders before save.
	emaillog.ReturnMsgValidator = emaillogDescReturnMsg.Validators[0].(func(string) error)
	smslogMixin := schema.SmsLog{}.Mixin()
	smslogMixinFields1 := smslogMixin[1].Fields()
	_ = smslogMixinFields1
	smslogMixinFields2 := smslogMixin[2].Fields()
	_ = smslogMixinFields2
	smslogMixinFields3 := smslogMixin[3].Fields()
	_ = smslogMixinFields3
	smslogMixinFields4 := smslogMixin[4].Fields()
	_ = smslogMixinFields4
	smslogFields := schema.SmsLog{}.Fields()
	_ = smslogFields
	// smslogDescCreateTime is the schema descriptor for create_time field.
	smslogDescCreateTime := smslogMixinFields1[0].Descriptor()
	// smslog.DefaultCreateTime holds the default value on creation for the create_time field.
	smslog.DefaultCreateTime = smslogDescCreateTime.Default.(func() int64)
	// smslogDescCreateBy is the schema descriptor for create_by field.
	smslogDescCreateBy := smslogMixinFields2[0].Descriptor()
	// smslog.DefaultCreateBy holds the default value on creation for the create_by field.
	smslog.DefaultCreateBy = smslogDescCreateBy.Default.(uint64)
	// smslogDescUpdateTime is the schema descriptor for update_time field.
	smslogDescUpdateTime := smslogMixinFields3[0].Descriptor()
	// smslog.DefaultUpdateTime holds the default value on creation for the update_time field.
	smslog.DefaultUpdateTime = smslogDescUpdateTime.Default.(func() int64)
	// smslog.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	smslog.UpdateDefaultUpdateTime = smslogDescUpdateTime.UpdateDefault.(func() int64)
	// smslogDescUpdateBy is the schema descriptor for update_by field.
	smslogDescUpdateBy := smslogMixinFields4[0].Descriptor()
	// smslog.DefaultUpdateBy holds the default value on creation for the update_by field.
	smslog.DefaultUpdateBy = smslogDescUpdateBy.Default.(uint64)
	// smslogDescAppID is the schema descriptor for app_id field.
	smslogDescAppID := smslogFields[0].Descriptor()
	// smslog.DefaultAppID holds the default value on creation for the app_id field.
	smslog.DefaultAppID = smslogDescAppID.Default.(uint64)
	// smslogDescDialCode is the schema descriptor for dial_code field.
	smslogDescDialCode := smslogFields[1].Descriptor()
	// smslog.DefaultDialCode holds the default value on creation for the dial_code field.
	smslog.DefaultDialCode = smslogDescDialCode.Default.(string)
	// smslog.DialCodeValidator is a validator for the "dial_code" field. It is called by the builders before save.
	smslog.DialCodeValidator = smslogDescDialCode.Validators[0].(func(string) error)
	// smslogDescMobile is the schema descriptor for mobile field.
	smslogDescMobile := smslogFields[2].Descriptor()
	// smslog.DefaultMobile holds the default value on creation for the mobile field.
	smslog.DefaultMobile = smslogDescMobile.Default.(string)
	// smslog.MobileValidator is a validator for the "mobile" field. It is called by the builders before save.
	smslog.MobileValidator = smslogDescMobile.Validators[0].(func(string) error)
	// smslogDescScope is the schema descriptor for scope field.
	smslogDescScope := smslogFields[3].Descriptor()
	// smslog.DefaultScope holds the default value on creation for the scope field.
	smslog.DefaultScope = smslogDescScope.Default.(string)
	// smslog.ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	smslog.ScopeValidator = smslogDescScope.Validators[0].(func(string) error)
	// smslogDescTypeID is the schema descriptor for type_id field.
	smslogDescTypeID := smslogFields[4].Descriptor()
	// smslog.DefaultTypeID holds the default value on creation for the type_id field.
	smslog.DefaultTypeID = smslogDescTypeID.Default.(uint64)
	// smslogDescGateway is the schema descriptor for gateway field.
	smslogDescGateway := smslogFields[5].Descriptor()
	// smslog.DefaultGateway holds the default value on creation for the gateway field.
	smslog.DefaultGateway = smslogDescGateway.Default.(string)
	// smslog.GatewayValidator is a validator for the "gateway" field. It is called by the builders before save.
	smslog.GatewayValidator = smslogDescGateway.Validators[0].(func(string) error)
	// smslogDescIP is the schema descriptor for ip field.
	smslogDescIP := smslogFields[6].Descriptor()
	// smslog.DefaultIP holds the default value on creation for the ip field.
	smslog.DefaultIP = smslogDescIP.Default.(string)
	// smslog.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	smslog.IPValidator = smslogDescIP.Validators[0].(func(string) error)
	// smslogDescTemplateID is the schema descriptor for template_id field.
	smslogDescTemplateID := smslogFields[7].Descriptor()
	// smslog.DefaultTemplateID holds the default value on creation for the template_id field.
	smslog.DefaultTemplateID = smslogDescTemplateID.Default.(string)
	// smslog.TemplateIDValidator is a validator for the "template_id" field. It is called by the builders before save.
	smslog.TemplateIDValidator = smslogDescTemplateID.Validators[0].(func(string) error)
	// smslogDescTemplateText is the schema descriptor for template_text field.
	smslogDescTemplateText := smslogFields[8].Descriptor()
	// smslog.DefaultTemplateText holds the default value on creation for the template_text field.
	smslog.DefaultTemplateText = smslogDescTemplateText.Default.(string)
	// smslog.TemplateTextValidator is a validator for the "template_text" field. It is called by the builders before save.
	smslog.TemplateTextValidator = smslogDescTemplateText.Validators[0].(func(string) error)
	// smslogDescContent is the schema descriptor for content field.
	smslogDescContent := smslogFields[9].Descriptor()
	// smslog.DefaultContent holds the default value on creation for the content field.
	smslog.DefaultContent = smslogDescContent.Default.(string)
	// smslog.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	smslog.ContentValidator = smslogDescContent.Validators[0].(func(string) error)
	// smslogDescCheckCount is the schema descriptor for check_count field.
	smslogDescCheckCount := smslogFields[10].Descriptor()
	// smslog.DefaultCheckCount holds the default value on creation for the check_count field.
	smslog.DefaultCheckCount = smslogDescCheckCount.Default.(uint8)
	// smslogDescStatus is the schema descriptor for status field.
	smslogDescStatus := smslogFields[11].Descriptor()
	// smslog.DefaultStatus holds the default value on creation for the status field.
	smslog.DefaultStatus = smslogDescStatus.Default.(uint)
	// smslogDescReturnMsg is the schema descriptor for return_msg field.
	smslogDescReturnMsg := smslogFields[12].Descriptor()
	// smslog.DefaultReturnMsg holds the default value on creation for the return_msg field.
	smslog.DefaultReturnMsg = smslogDescReturnMsg.Default.(string)
	// smslog.ReturnMsgValidator is a validator for the "return_msg" field. It is called by the builders before save.
	smslog.ReturnMsgValidator = smslogDescReturnMsg.Validators[0].(func(string) error)
	sortMixin := schema.Sort{}.Mixin()
	sortMixinFields1 := sortMixin[1].Fields()
	_ = sortMixinFields1
	sortMixinFields2 := sortMixin[2].Fields()
	_ = sortMixinFields2
	sortMixinFields3 := sortMixin[3].Fields()
	_ = sortMixinFields3
	sortMixinFields4 := sortMixin[4].Fields()
	_ = sortMixinFields4
	sortMixinFields5 := sortMixin[5].Fields()
	_ = sortMixinFields5
	sortFields := schema.Sort{}.Fields()
	_ = sortFields
	// sortDescDeleteTime is the schema descriptor for delete_time field.
	sortDescDeleteTime := sortMixinFields1[0].Descriptor()
	// sort.DefaultDeleteTime holds the default value on creation for the delete_time field.
	sort.DefaultDeleteTime = sortDescDeleteTime.Default.(int64)
	// sortDescCreateTime is the schema descriptor for create_time field.
	sortDescCreateTime := sortMixinFields2[0].Descriptor()
	// sort.DefaultCreateTime holds the default value on creation for the create_time field.
	sort.DefaultCreateTime = sortDescCreateTime.Default.(func() int64)
	// sortDescCreateBy is the schema descriptor for create_by field.
	sortDescCreateBy := sortMixinFields3[0].Descriptor()
	// sort.DefaultCreateBy holds the default value on creation for the create_by field.
	sort.DefaultCreateBy = sortDescCreateBy.Default.(uint64)
	// sortDescUpdateTime is the schema descriptor for update_time field.
	sortDescUpdateTime := sortMixinFields4[0].Descriptor()
	// sort.DefaultUpdateTime holds the default value on creation for the update_time field.
	sort.DefaultUpdateTime = sortDescUpdateTime.Default.(func() int64)
	// sort.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	sort.UpdateDefaultUpdateTime = sortDescUpdateTime.UpdateDefault.(func() int64)
	// sortDescUpdateBy is the schema descriptor for update_by field.
	sortDescUpdateBy := sortMixinFields5[0].Descriptor()
	// sort.DefaultUpdateBy holds the default value on creation for the update_by field.
	sort.DefaultUpdateBy = sortDescUpdateBy.Default.(uint64)
	// sortDescUUID is the schema descriptor for uuid field.
	sortDescUUID := sortFields[0].Descriptor()
	// sort.DefaultUUID holds the default value on creation for the uuid field.
	sort.DefaultUUID = sortDescUUID.Default.(func() *uuid.UUID)
	// sortDescParentID is the schema descriptor for parent_id field.
	sortDescParentID := sortFields[1].Descriptor()
	// sort.DefaultParentID holds the default value on creation for the parent_id field.
	sort.DefaultParentID = sortDescParentID.Default.(uint64)
	// sortDescTitle is the schema descriptor for title field.
	sortDescTitle := sortFields[2].Descriptor()
	// sort.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	sort.TitleValidator = sortDescTitle.Validators[0].(func(string) error)
	// sortDescParentList is the schema descriptor for parent_list field.
	sortDescParentList := sortFields[3].Descriptor()
	// sort.DefaultParentList holds the default value on creation for the parent_list field.
	sort.DefaultParentList = sortDescParentList.Default.(string)
	// sort.ParentListValidator is a validator for the "parent_list" field. It is called by the builders before save.
	sort.ParentListValidator = sortDescParentList.Validators[0].(func(string) error)
	// sortDescIconID is the schema descriptor for icon_id field.
	sortDescIconID := sortFields[4].Descriptor()
	// sort.DefaultIconID holds the default value on creation for the icon_id field.
	sort.DefaultIconID = sortDescIconID.Default.(uint64)
	// sortDescIconURL is the schema descriptor for icon_url field.
	sortDescIconURL := sortFields[5].Descriptor()
	// sort.IconURLValidator is a validator for the "icon_url" field. It is called by the builders before save.
	sort.IconURLValidator = sortDescIconURL.Validators[0].(func(string) error)
	// sortDescDisplayOrder is the schema descriptor for display_order field.
	sortDescDisplayOrder := sortFields[6].Descriptor()
	// sort.DefaultDisplayOrder holds the default value on creation for the display_order field.
	sort.DefaultDisplayOrder = sortDescDisplayOrder.Default.(uint16)
	// sort.DisplayOrderValidator is a validator for the "display_order" field. It is called by the builders before save.
	sort.DisplayOrderValidator = sortDescDisplayOrder.Validators[0].(func(uint16) error)
	// sortDescLevel is the schema descriptor for level field.
	sortDescLevel := sortFields[7].Descriptor()
	// sort.DefaultLevel holds the default value on creation for the level field.
	sort.DefaultLevel = sortDescLevel.Default.(uint)
	// sort.LevelValidator is a validator for the "level" field. It is called by the builders before save.
	sort.LevelValidator = sortDescLevel.Validators[0].(func(uint) error)
	// sortDescStatus is the schema descriptor for status field.
	sortDescStatus := sortFields[8].Descriptor()
	// sort.DefaultStatus holds the default value on creation for the status field.
	sort.DefaultStatus = sortDescStatus.Default.(uint)
	// sort.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	sort.StatusValidator = sortDescStatus.Validators[0].(func(uint) error)
	userMixin := schema.User{}.Mixin()
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userMixinFields2 := userMixin[2].Fields()
	_ = userMixinFields2
	userMixinFields3 := userMixin[3].Fields()
	_ = userMixinFields3
	userMixinFields4 := userMixin[4].Fields()
	_ = userMixinFields4
	userMixinFields5 := userMixin[5].Fields()
	_ = userMixinFields5
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescDeleteTime is the schema descriptor for delete_time field.
	userDescDeleteTime := userMixinFields1[0].Descriptor()
	// user.DefaultDeleteTime holds the default value on creation for the delete_time field.
	user.DefaultDeleteTime = userDescDeleteTime.Default.(int64)
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userMixinFields2[0].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() int64)
	// userDescCreateBy is the schema descriptor for create_by field.
	userDescCreateBy := userMixinFields3[0].Descriptor()
	// user.DefaultCreateBy holds the default value on creation for the create_by field.
	user.DefaultCreateBy = userDescCreateBy.Default.(uint64)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userMixinFields4[0].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() int64)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() int64)
	// userDescUpdateBy is the schema descriptor for update_by field.
	userDescUpdateBy := userMixinFields5[0].Descriptor()
	// user.DefaultUpdateBy holds the default value on creation for the update_by field.
	user.DefaultUpdateBy = userDescUpdateBy.Default.(uint64)
	// userDescUUID is the schema descriptor for uuid field.
	userDescUUID := userFields[0].Descriptor()
	// user.DefaultUUID holds the default value on creation for the uuid field.
	user.DefaultUUID = userDescUUID.Default.(func() uuid.UUID)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.DefaultUsername holds the default value on creation for the username field.
	user.DefaultUsername = userDescUsername.Default.(string)
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[2].Descriptor()
	// user.DefaultNickname holds the default value on creation for the nickname field.
	user.DefaultNickname = userDescNickname.Default.(string)
	// user.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	user.NicknameValidator = userDescNickname.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[3].Descriptor()
	// user.DefaultPassword holds the default value on creation for the password field.
	user.DefaultPassword = userDescPassword.Default.(string)
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescDialCode is the schema descriptor for dial_code field.
	userDescDialCode := userFields[4].Descriptor()
	// user.DefaultDialCode holds the default value on creation for the dial_code field.
	user.DefaultDialCode = userDescDialCode.Default.(string)
	// user.DialCodeValidator is a validator for the "dial_code" field. It is called by the builders before save.
	user.DialCodeValidator = userDescDialCode.Validators[0].(func(string) error)
	// userDescMobile is the schema descriptor for mobile field.
	userDescMobile := userFields[5].Descriptor()
	// user.DefaultMobile holds the default value on creation for the mobile field.
	user.DefaultMobile = userDescMobile.Default.(string)
	// user.MobileValidator is a validator for the "mobile" field. It is called by the builders before save.
	user.MobileValidator = userDescMobile.Validators[0].(func(string) error)
	// userDescMobileHash is the schema descriptor for mobile_hash field.
	userDescMobileHash := userFields[6].Descriptor()
	// user.DefaultMobileHash holds the default value on creation for the mobile_hash field.
	user.DefaultMobileHash = userDescMobileHash.Default.(string)
	// user.MobileHashValidator is a validator for the "mobile_hash" field. It is called by the builders before save.
	user.MobileHashValidator = userDescMobileHash.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[7].Descriptor()
	// user.DefaultEmail holds the default value on creation for the email field.
	user.DefaultEmail = userDescEmail.Default.(string)
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescEmailHash is the schema descriptor for email_hash field.
	userDescEmailHash := userFields[8].Descriptor()
	// user.DefaultEmailHash holds the default value on creation for the email_hash field.
	user.DefaultEmailHash = userDescEmailHash.Default.(string)
	// user.EmailHashValidator is a validator for the "email_hash" field. It is called by the builders before save.
	user.EmailHashValidator = userDescEmailHash.Validators[0].(func(string) error)
	// userDescAvatar is the schema descriptor for avatar field.
	userDescAvatar := userFields[9].Descriptor()
	// user.DefaultAvatar holds the default value on creation for the avatar field.
	user.DefaultAvatar = userDescAvatar.Default.(string)
	// user.AvatarValidator is a validator for the "avatar" field. It is called by the builders before save.
	user.AvatarValidator = userDescAvatar.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[10].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescSex is the schema descriptor for sex field.
	userDescSex := userFields[11].Descriptor()
	// user.DefaultSex holds the default value on creation for the sex field.
	user.DefaultSex = userDescSex.Default.(uint)
	// user.SexValidator is a validator for the "sex" field. It is called by the builders before save.
	user.SexValidator = userDescSex.Validators[0].(func(uint) error)
	// userDescBirthday is the schema descriptor for birthday field.
	userDescBirthday := userFields[12].Descriptor()
	// user.DefaultBirthday holds the default value on creation for the birthday field.
	user.DefaultBirthday = userDescBirthday.Default.(uint64)
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[13].Descriptor()
	// user.DefaultAge holds the default value on creation for the age field.
	user.DefaultAge = userDescAge.Default.(uint)
	// userDescLastLoginIP is the schema descriptor for last_login_ip field.
	userDescLastLoginIP := userFields[14].Descriptor()
	// user.DefaultLastLoginIP holds the default value on creation for the last_login_ip field.
	user.DefaultLastLoginIP = userDescLastLoginIP.Default.(string)
	// user.LastLoginIPValidator is a validator for the "last_login_ip" field. It is called by the builders before save.
	user.LastLoginIPValidator = userDescLastLoginIP.Validators[0].(func(string) error)
	// userDescLastLoginTime is the schema descriptor for last_login_time field.
	userDescLastLoginTime := userFields[15].Descriptor()
	// user.DefaultLastLoginTime holds the default value on creation for the last_login_time field.
	user.DefaultLastLoginTime = userDescLastLoginTime.Default.(uint64)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[16].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(uint)
}
