// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/boshangad/v1/ent/app"
	"github.com/boshangad/v1/ent/internal"
	"github.com/boshangad/v1/ent/predicate"
	"github.com/boshangad/v1/ent/smslog"
)

// SmsLogQuery is the builder for querying SmsLog entities.
type SmsLogQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.SmsLog
	// eager-loading edges.
	withApp   *AppQuery
	modifiers []func(s *sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SmsLogQuery builder.
func (slq *SmsLogQuery) Where(ps ...predicate.SmsLog) *SmsLogQuery {
	slq.predicates = append(slq.predicates, ps...)
	return slq
}

// Limit adds a limit step to the query.
func (slq *SmsLogQuery) Limit(limit int) *SmsLogQuery {
	slq.limit = &limit
	return slq
}

// Offset adds an offset step to the query.
func (slq *SmsLogQuery) Offset(offset int) *SmsLogQuery {
	slq.offset = &offset
	return slq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (slq *SmsLogQuery) Unique(unique bool) *SmsLogQuery {
	slq.unique = &unique
	return slq
}

// Order adds an order step to the query.
func (slq *SmsLogQuery) Order(o ...OrderFunc) *SmsLogQuery {
	slq.order = append(slq.order, o...)
	return slq
}

// QueryApp chains the current query on the "app" edge.
func (slq *SmsLogQuery) QueryApp() *AppQuery {
	query := &AppQuery{config: slq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := slq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := slq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(smslog.Table, smslog.FieldID, selector),
			sqlgraph.To(app.Table, app.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, smslog.AppTable, smslog.AppColumn),
		)
		schemaConfig := slq.schemaConfig
		step.To.Schema = schemaConfig.App
		step.Edge.Schema = schemaConfig.SmsLog
		fromU = sqlgraph.SetNeighbors(slq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SmsLog entity from the query.
// Returns a *NotFoundError when no SmsLog was found.
func (slq *SmsLogQuery) First(ctx context.Context) (*SmsLog, error) {
	nodes, err := slq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{smslog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (slq *SmsLogQuery) FirstX(ctx context.Context) *SmsLog {
	node, err := slq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SmsLog ID from the query.
// Returns a *NotFoundError when no SmsLog ID was found.
func (slq *SmsLogQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = slq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{smslog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (slq *SmsLogQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := slq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SmsLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one SmsLog entity is not found.
// Returns a *NotFoundError when no SmsLog entities are found.
func (slq *SmsLogQuery) Only(ctx context.Context) (*SmsLog, error) {
	nodes, err := slq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{smslog.Label}
	default:
		return nil, &NotSingularError{smslog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (slq *SmsLogQuery) OnlyX(ctx context.Context) *SmsLog {
	node, err := slq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SmsLog ID in the query.
// Returns a *NotSingularError when exactly one SmsLog ID is not found.
// Returns a *NotFoundError when no entities are found.
func (slq *SmsLogQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = slq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{smslog.Label}
	default:
		err = &NotSingularError{smslog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (slq *SmsLogQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := slq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SmsLogs.
func (slq *SmsLogQuery) All(ctx context.Context) ([]*SmsLog, error) {
	if err := slq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return slq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (slq *SmsLogQuery) AllX(ctx context.Context) []*SmsLog {
	nodes, err := slq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SmsLog IDs.
func (slq *SmsLogQuery) IDs(ctx context.Context) ([]uint64, error) {
	var ids []uint64
	if err := slq.Select(smslog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (slq *SmsLogQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := slq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (slq *SmsLogQuery) Count(ctx context.Context) (int, error) {
	if err := slq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return slq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (slq *SmsLogQuery) CountX(ctx context.Context) int {
	count, err := slq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (slq *SmsLogQuery) Exist(ctx context.Context) (bool, error) {
	if err := slq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return slq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (slq *SmsLogQuery) ExistX(ctx context.Context) bool {
	exist, err := slq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SmsLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (slq *SmsLogQuery) Clone() *SmsLogQuery {
	if slq == nil {
		return nil
	}
	return &SmsLogQuery{
		config:     slq.config,
		limit:      slq.limit,
		offset:     slq.offset,
		order:      append([]OrderFunc{}, slq.order...),
		predicates: append([]predicate.SmsLog{}, slq.predicates...),
		withApp:    slq.withApp.Clone(),
		// clone intermediate query.
		sql:  slq.sql.Clone(),
		path: slq.path,
	}
}

// WithApp tells the query-builder to eager-load the nodes that are connected to
// the "app" edge. The optional arguments are used to configure the query builder of the edge.
func (slq *SmsLogQuery) WithApp(opts ...func(*AppQuery)) *SmsLogQuery {
	query := &AppQuery{config: slq.config}
	for _, opt := range opts {
		opt(query)
	}
	slq.withApp = query
	return slq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime int64 `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SmsLog.Query().
//		GroupBy(smslog.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (slq *SmsLogQuery) GroupBy(field string, fields ...string) *SmsLogGroupBy {
	group := &SmsLogGroupBy{config: slq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := slq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return slq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime int64 `json:"create_time,omitempty"`
//	}
//
//	client.SmsLog.Query().
//		Select(smslog.FieldCreateTime).
//		Scan(ctx, &v)
//
func (slq *SmsLogQuery) Select(fields ...string) *SmsLogSelect {
	slq.fields = append(slq.fields, fields...)
	return &SmsLogSelect{SmsLogQuery: slq}
}

func (slq *SmsLogQuery) prepareQuery(ctx context.Context) error {
	for _, f := range slq.fields {
		if !smslog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if slq.path != nil {
		prev, err := slq.path(ctx)
		if err != nil {
			return err
		}
		slq.sql = prev
	}
	return nil
}

func (slq *SmsLogQuery) sqlAll(ctx context.Context) ([]*SmsLog, error) {
	var (
		nodes       = []*SmsLog{}
		_spec       = slq.querySpec()
		loadedTypes = [1]bool{
			slq.withApp != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &SmsLog{config: slq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(slq.modifiers) > 0 {
		_spec.Modifiers = slq.modifiers
	}
	_spec.Node.Schema = slq.schemaConfig.SmsLog
	ctx = internal.NewSchemaConfigContext(ctx, slq.schemaConfig)
	if err := sqlgraph.QueryNodes(ctx, slq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := slq.withApp; query != nil {
		ids := make([]uint64, 0, len(nodes))
		nodeids := make(map[uint64][]*SmsLog)
		for i := range nodes {
			fk := nodes[i].AppID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(app.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "app_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.App = n
			}
		}
	}

	return nodes, nil
}

func (slq *SmsLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := slq.querySpec()
	if len(slq.modifiers) > 0 {
		_spec.Modifiers = slq.modifiers
	}
	_spec.Node.Schema = slq.schemaConfig.SmsLog
	ctx = internal.NewSchemaConfigContext(ctx, slq.schemaConfig)
	return sqlgraph.CountNodes(ctx, slq.driver, _spec)
}

func (slq *SmsLogQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := slq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (slq *SmsLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   smslog.Table,
			Columns: smslog.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: smslog.FieldID,
			},
		},
		From:   slq.sql,
		Unique: true,
	}
	if unique := slq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := slq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, smslog.FieldID)
		for i := range fields {
			if fields[i] != smslog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := slq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := slq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := slq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := slq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (slq *SmsLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(slq.driver.Dialect())
	t1 := builder.Table(smslog.Table)
	columns := slq.fields
	if len(columns) == 0 {
		columns = smslog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if slq.sql != nil {
		selector = slq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, m := range slq.modifiers {
		m(selector)
	}
	t1.Schema(slq.schemaConfig.SmsLog)
	ctx = internal.NewSchemaConfigContext(ctx, slq.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range slq.predicates {
		p(selector)
	}
	for _, p := range slq.order {
		p(selector)
	}
	if offset := slq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := slq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (slq *SmsLogQuery) ForUpdate(opts ...sql.LockOption) *SmsLogQuery {
	if slq.driver.Dialect() == dialect.Postgres {
		slq.Unique(false)
	}
	slq.modifiers = append(slq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return slq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (slq *SmsLogQuery) ForShare(opts ...sql.LockOption) *SmsLogQuery {
	if slq.driver.Dialect() == dialect.Postgres {
		slq.Unique(false)
	}
	slq.modifiers = append(slq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return slq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (slq *SmsLogQuery) Modify(modifiers ...func(s *sql.Selector)) *SmsLogSelect {
	slq.modifiers = append(slq.modifiers, modifiers...)
	return slq.Select()
}

// SmsLogGroupBy is the group-by builder for SmsLog entities.
type SmsLogGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (slgb *SmsLogGroupBy) Aggregate(fns ...AggregateFunc) *SmsLogGroupBy {
	slgb.fns = append(slgb.fns, fns...)
	return slgb
}

// Scan applies the group-by query and scans the result into the given value.
func (slgb *SmsLogGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := slgb.path(ctx)
	if err != nil {
		return err
	}
	slgb.sql = query
	return slgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (slgb *SmsLogGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := slgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (slgb *SmsLogGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(slgb.fields) > 1 {
		return nil, errors.New("ent: SmsLogGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := slgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (slgb *SmsLogGroupBy) StringsX(ctx context.Context) []string {
	v, err := slgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (slgb *SmsLogGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = slgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{smslog.Label}
	default:
		err = fmt.Errorf("ent: SmsLogGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (slgb *SmsLogGroupBy) StringX(ctx context.Context) string {
	v, err := slgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (slgb *SmsLogGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(slgb.fields) > 1 {
		return nil, errors.New("ent: SmsLogGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := slgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (slgb *SmsLogGroupBy) IntsX(ctx context.Context) []int {
	v, err := slgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (slgb *SmsLogGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = slgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{smslog.Label}
	default:
		err = fmt.Errorf("ent: SmsLogGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (slgb *SmsLogGroupBy) IntX(ctx context.Context) int {
	v, err := slgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (slgb *SmsLogGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(slgb.fields) > 1 {
		return nil, errors.New("ent: SmsLogGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := slgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (slgb *SmsLogGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := slgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (slgb *SmsLogGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = slgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{smslog.Label}
	default:
		err = fmt.Errorf("ent: SmsLogGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (slgb *SmsLogGroupBy) Float64X(ctx context.Context) float64 {
	v, err := slgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (slgb *SmsLogGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(slgb.fields) > 1 {
		return nil, errors.New("ent: SmsLogGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := slgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (slgb *SmsLogGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := slgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (slgb *SmsLogGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = slgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{smslog.Label}
	default:
		err = fmt.Errorf("ent: SmsLogGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (slgb *SmsLogGroupBy) BoolX(ctx context.Context) bool {
	v, err := slgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (slgb *SmsLogGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range slgb.fields {
		if !smslog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := slgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := slgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (slgb *SmsLogGroupBy) sqlQuery() *sql.Selector {
	selector := slgb.sql.Select()
	aggregation := make([]string, 0, len(slgb.fns))
	for _, fn := range slgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(slgb.fields)+len(slgb.fns))
		for _, f := range slgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(slgb.fields...)...)
}

// SmsLogSelect is the builder for selecting fields of SmsLog entities.
type SmsLogSelect struct {
	*SmsLogQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (sls *SmsLogSelect) Scan(ctx context.Context, v interface{}) error {
	if err := sls.prepareQuery(ctx); err != nil {
		return err
	}
	sls.sql = sls.SmsLogQuery.sqlQuery(ctx)
	return sls.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (sls *SmsLogSelect) ScanX(ctx context.Context, v interface{}) {
	if err := sls.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (sls *SmsLogSelect) Strings(ctx context.Context) ([]string, error) {
	if len(sls.fields) > 1 {
		return nil, errors.New("ent: SmsLogSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := sls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (sls *SmsLogSelect) StringsX(ctx context.Context) []string {
	v, err := sls.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (sls *SmsLogSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = sls.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{smslog.Label}
	default:
		err = fmt.Errorf("ent: SmsLogSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (sls *SmsLogSelect) StringX(ctx context.Context) string {
	v, err := sls.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (sls *SmsLogSelect) Ints(ctx context.Context) ([]int, error) {
	if len(sls.fields) > 1 {
		return nil, errors.New("ent: SmsLogSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := sls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (sls *SmsLogSelect) IntsX(ctx context.Context) []int {
	v, err := sls.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (sls *SmsLogSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = sls.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{smslog.Label}
	default:
		err = fmt.Errorf("ent: SmsLogSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (sls *SmsLogSelect) IntX(ctx context.Context) int {
	v, err := sls.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (sls *SmsLogSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(sls.fields) > 1 {
		return nil, errors.New("ent: SmsLogSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := sls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (sls *SmsLogSelect) Float64sX(ctx context.Context) []float64 {
	v, err := sls.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (sls *SmsLogSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = sls.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{smslog.Label}
	default:
		err = fmt.Errorf("ent: SmsLogSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (sls *SmsLogSelect) Float64X(ctx context.Context) float64 {
	v, err := sls.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (sls *SmsLogSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(sls.fields) > 1 {
		return nil, errors.New("ent: SmsLogSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := sls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (sls *SmsLogSelect) BoolsX(ctx context.Context) []bool {
	v, err := sls.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (sls *SmsLogSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = sls.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{smslog.Label}
	default:
		err = fmt.Errorf("ent: SmsLogSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (sls *SmsLogSelect) BoolX(ctx context.Context) bool {
	v, err := sls.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sls *SmsLogSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := sls.sql.Query()
	if err := sls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (sls *SmsLogSelect) Modify(modifiers ...func(s *sql.Selector)) *SmsLogSelect {
	sls.modifiers = append(sls.modifiers, modifiers...)
	return sls
}
