#应用配置项
app:
  baseurl: http://localhost:8080
  listen: :8080
  name: test
  rootpath: ""
# DB数据库
db:
  driver: mysql
  host: 127.0.0.1:3306
  username: root
  password: "xingyun"
  dbname: "ad_boshang"
  maxIdleConns: "10"
# 日志功能
log:
  director: ""
  Level: "debug"
  showLine: true
  stacktraceKey: ""
  encodeLevel: "LowercaseLevelEncoder"
  logInConsole: true
  prefix: ""
  format: "row"
  maxSize: 0
  maxBackups: 0
  maxAge: 0
  compress: true
disk:
  default: ucloud
  disks:
    ucloud:
      bucketName: boshang
      accessKeyId: TOKEN_8e7f7467-4b29-4310-8d4d-796076d02322
      accessKeySecret: 2f2e7896-d798-47a5-afd5-cedece95d777
cache:
  type: "file"
  director: ""
  keyPrefix: ""
  cacheFileSuffix: ""
  directoryLevel: 0
  gcProbability: 0
  fileMode: 0644
  dirMode: 0744
sms:
  defaults: ["aliyun", "ucloud"]
  gateways:
    aliyun:
      gateway: aliyun
      accessKeyId: cdervbhyjuhygtvf
      accessKeySecret: jefjekcedc
      signName: "14567"
    ucloud:
      gateway: ucloud
      privateKey:
      publicKey: hgkuytredfgh
      signName: ""
      projectId: org-575
captcha:
  image:
    type: image
    length: 6
  audio:
    type: audio
    length: 6