// Code generated by entc, DO NOT EDIT.

package appusertoken

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the appusertoken type in the database.
	Label = "app_user_token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// FieldAppUserID holds the string denoting the app_user_id field in the database.
	FieldAppUserID = "app_user_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldClientVersion holds the string denoting the client_version field in the database.
	FieldClientVersion = "client_version"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldExpireTime holds the string denoting the expire_time field in the database.
	FieldExpireTime = "expire_time"
	// EdgeApp holds the string denoting the app edge name in mutations.
	EdgeApp = "app"
	// EdgeAppUser holds the string denoting the appuser edge name in mutations.
	EdgeAppUser = "appUser"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the appusertoken in the database.
	Table = "app_user_token"
	// AppTable is the table that holds the app relation/edge.
	AppTable = "app_user_token"
	// AppInverseTable is the table name for the App entity.
	// It exists in this package in order to avoid circular dependency with the "app" package.
	AppInverseTable = "app"
	// AppColumn is the table column denoting the app relation/edge.
	AppColumn = "app_id"
	// AppUserTable is the table that holds the appUser relation/edge.
	AppUserTable = "app_user_token"
	// AppUserInverseTable is the table name for the AppUser entity.
	// It exists in this package in order to avoid circular dependency with the "appuser" package.
	AppUserInverseTable = "app_user"
	// AppUserColumn is the table column denoting the appUser relation/edge.
	AppUserColumn = "app_user_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "app_user_token"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "user"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for appusertoken fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldAppID,
	FieldAppUserID,
	FieldUserID,
	FieldClientVersion,
	FieldUUID,
	FieldIP,
	FieldExpireTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() int64
	// DefaultAppID holds the default value on creation for the "app_id" field.
	DefaultAppID uint64
	// DefaultAppUserID holds the default value on creation for the "app_user_id" field.
	DefaultAppUserID uint64
	// DefaultUserID holds the default value on creation for the "user_id" field.
	DefaultUserID uint64
	// DefaultClientVersion holds the default value on creation for the "client_version" field.
	DefaultClientVersion string
	// ClientVersionValidator is a validator for the "client_version" field. It is called by the builders before save.
	ClientVersionValidator func(string) error
	// DefaultUUID holds the default value on creation for the "uuid" field.
	DefaultUUID func() *uuid.UUID
	// DefaultIP holds the default value on creation for the "ip" field.
	DefaultIP string
	// IPValidator is a validator for the "ip" field. It is called by the builders before save.
	IPValidator func(string) error
	// DefaultExpireTime holds the default value on creation for the "expire_time" field.
	DefaultExpireTime int64
)
